disabled_rules:
  - line_length
  - trailing_whitespace
  - force_cast
  - colon
  - identifier_name
  - legacy_constructor
  - type_name
  - control_statement
  - force_try
  - function_parameter_count
  - void_return
  - fallthrough
  - empty_parentheses_with_trailing_closure
  - for_where
  - private_over_fileprivate
  - discarded_notification_center_observer
  - unused_closure_parameter
  - large_tuple
  - cyclomatic_complexity
  - redundant_string_enum_value
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
type_body_length:
  warning: 600
  error: 1200
function_body_length:
  warning: 80
file_length:
  warning: 750
  error: 1200
file_header:
  required_pattern: |
    \/\/
    \/\/  .*?\.swift
    \/\/  Confer
    \/\/  Copyright © \d{4} tech.gaire.confer\. All rights reserved\.
    \/\/

switch_case_alignment:
  indented_cases: true

opt_in_rules:
  - operator_usage_whitespace
  - overridden_super_call
  - vertical_whitespace_closing_braces
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_string
  - empty_xctest_method
  - explicit_enum_raw_value
  - explicit_init
  - explicit_self
  - file_header
  - first_where
  - force_unwrapping
  - joined_default_parameter
  - last_where
  - leading_whitespace
  - lower_acl_than_parent
  - multiline_parameters
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_private_declaration
  - xct_specific_matcher
  - yoda_condition
  - attributes
  - collection_alignment
  - missing_docs
